version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            pip -q install -r requirements.txt
          name: loading dependencies
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
